version: '3' # Version of the Docker Compose file format

services:
    nginx-proxy:
        container_name: nginx-proxy
        image: nginxproxy/nginx-proxy:1.5.1-alpine
        restart: "always" # Always restart container
        labels:
          - "com.github.nginx-proxy.nginx"
        ports:
         - "80:80"
         - "443:443"
        networks:
         - nginx-proxy
        volumes: # Volumes needed for container to configure proixes and access certificates genereated by Let's Encrypt companion container
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - ./config/certs:/etc/nginx/certs
         - ./config/conf.d:/etc/nginx/conf.d
         - ./config/vhost.d:/etc/nginx/vhost.d
         - ./sites/proxy:/usr/share/nginx/html

    nginx-proxy-acme:
      # nginx_location.conf
        container_name: nginx-proxy-acme
        image: nginxproxy/acme-companion:2.2.10
        restart: always
        networks:
         - nginx-proxy
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock:ro
         - ./config/certs:/etc/nginx/certs
         - ./config/conf.d:/etc/nginx/conf.d
         - ./config/vhost.d:/etc/nginx/vhost.d
         - ./sites/proxy:/usr/share/nginx/html
        environment:
        - "NGINX_PROXY_CONTAINER=nginx-proxy"
        - "DEFAULT_EMAIL=my_email@acme.com"
        depends_on: # Make sure we start nginx proxy container first
        - nginx-proxy

    my-website:
        container_name: my-website
        image: nginx:1.25.4-alpine
        restart: always
        networks:
         - nginx-proxy
        volumes:
        - ./sites/my-website:/usr/share/nginx/html
        - ./config/conf.d/my-website.conf:/etc/nginx/conf.d/default.conf
        environment:
        - "VIRTUAL_HOST=my-website.com"
        - "LETSENCRYPT_HOST=my-website.com"

networks:
    nginx-proxy: # Name of our shared network that containers will use        