CREATE TABLE [finance].INVOICE (
      ID INT IDENTITY(1,1) NOT NULL
    , INVOICE_NUMBER VARCHAR(200)
    , INVOICE_DATE DATE
    , CUSTOMER_ID INT
    , PRODUCT_ID INT
    , AMOUNT DECIMAL
    , PAID VARCHAR(1)
    , CONSTRAINT PK_ID PRIMARY KEY CLUSTERED ("ID")
    , CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY ("CUSTOMER_ID") REFERENCES "sales"."CUSTOMER" ("ID")
    , CONSTRAINT FK_PRODUCT_ID FOREIGN KEY ("PRODUCT_ID") REFERENCES "warehouse"."PRODUCT" ("ID")
);
