CREATE TABLE [warehouse].PRODUCT (
      ID INT IDENTITY(1,1) NOT NULL
    , NAME VARCHAR(200)
    , PRICE VARCHAR(200)
    , STOCK VARCHAR(200)
    , SALE VARCHAR(1)
    , CONSTRAINT PK_ID PRIMARY KEY CLUSTERED ("ID")
);
